import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  formContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  signUpButton: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E71C35',
    borderRadius: 5,
    marginLeft: 50,
    marginRight: 50,
    marginTop: 20,
    height: 30,
    backgroundColor: '#E71C35',
  },
  buttonText: {
    color: 'white',
  },
  nameInputContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
    height: 36,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#d3d3d3',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 5,
  },
  emailInputContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
    height: 36,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#d3d3d3',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 5,
  },
  passwordInputContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
    height: 36,
    borderWidth: 1,
    borderColor: '#d3d3d3',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 5,
  },
  nameErrorContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
    height: 36,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#a94442',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 5,
  },
  emailErrorContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
    height: 36,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#a94442',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 5,
  },
  passwordErrorContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
    height: 36,
    borderWidth: 1,
    borderColor: '#a94442',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 5,
  },
  formInput: {
    flex: 12,
    marginLeft: 10,
    fontSize: 17,
  },
  formIcon: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 2,
  },
  errorText: {
    fontSize: 17,
    color: '#a94442',
    alignSelf: 'center',
    marginBottom: 10,
  },
  isFetching: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 50,
    marginRight: 50,
    marginTop: 10,
    height: 30,
  },
  signInTextButton: {
    color: 'blue',
    textDecorationLine: 'underline',
  },
});
